MvcCoreS3Post/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace MvcCoreS3Post.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MvcCoreS3Post/Controllers/UploadFileController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MvcCoreS3Post.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MvcCoreS3Post.Controllers
{
    public class UploadFileController : Controller
    {
        private ServicesAWSS3 servicesAWSS3;

        public UploadFileController(ServicesAWSS3 servicesAWSS)
        {
            this.servicesAWSS3 = servicesAWSS;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ListFiles()
        {
            List<String> files = await this.servicesAWSS3.GetAllFiles();

            return View(files);
        }

        public IActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Upload(IFormFile file)
        {
            using (MemoryStream m = new MemoryStream())
            {
                file.CopyTo(m);
                await this.servicesAWSS3.UploadFileinBucket(m, file.FileName);
            }

            return RedirectToAction("Index");
        }

        public IActionResult UploadChangeName()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadChangeName(IFormFile file)
        {
            using (MemoryStream m = new MemoryStream())
            {
                file.CopyTo(m);
                await this.servicesAWSS3.UploadFileChangeName(m, file.FileName);
            }

            return RedirectToAction("Index");
        }

        public IActionResult UploadDirectory()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadDirectory(IFormFile file)
        {
            using (MemoryStream m = new MemoryStream())
            {
                file.CopyTo(m);
                await this.servicesAWSS3.UploadFileinDirectoryBucket(m, file.FileName);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> FileAWS(string filename)
        {
            Stream stream = await this.servicesAWSS3.GetFile(filename);
            return File(stream, "image/jpg");
        }

        public IActionResult FileImg(string filename)
        {
            ViewData["img"] = "https://uploadfile-bucket-ans.s3.amazonaws.com/" + filename;
            return View();
        }

      
    }
}

MvcCoreS3Post/Views/Home/Index.cshtml
<h1>AWS Application</h1>

MvcCoreS3Post/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <title>@ViewData["Title"]</title>
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
    <!-- Custom styles for this template -->
    @*<link href="~/css/jumbotron.css" rel="stylesheet" />*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            @*<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-primary">*@
            <a class="navbar-brand" href="#">
                <img src="~/images/deadpool_PNG15.png" style="width:40px;" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="Home"
                           asp-action="Index">
                            <i class="bi bi-globe2"></i>
                            Home <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" asp-controller="UploadFile"
                           asp-action="Index">
                            Upload File S3 AWS
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="http://example.com"
                           id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                           aria-expanded="false">Ejemplos</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown01">
                            <a class="dropdown-item"
                               asp-controller="Home"
                               asp-action="Index">Home</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>


    <footer class="container">
        <p>&copy; Company 2021</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

MvcCoreS3Post/Views/UploadFile/FileImg.cshtml
@{
    ViewData["Title"] = "FileImg";
    String data = ViewData["img"] as String;
}

<h1>FileImg</h1>
<div>
    <img src="@data" width="500" height="500" />
</div>

MvcCoreS3Post/Views/UploadFile/Index.cshtml
<h1>Index</h1>


<ul class="list-group">
    <li class="list-group-item">
        <a asp-action="ListFiles" asp-controller="UploadFile">
            Files AWS
        </a>
    </li>
    <li class="list-group-item">
        <a asp-action="Upload" asp-controller="UploadFile">
            Upload en el Bucket
        </a>
    </li>
    <li class="list-group-item">
        <a asp-action="UploadChangeName" asp-controller="UploadFile">
            Upload renombrenado el fichero
        </a>
    </li>
    <li class="list-group-item">
        <a asp-action="UploadDirectory" asp-controller="UploadFile">
            Upload un direcotrio del Bucket
        </a>
    </li>
</ul>

MvcCoreS3Post/Views/UploadFile/ListFiles.cshtml
<h1>ListFileAWS</h1>

<a asp-action="Index" asp-controller="UploadFile">
    Volver Index
</a>

@if (Model != null)
{
<ul class="list-group">
    @foreach (String file in Model)
    {
        <li class="list-group-item">
            <a asp-action="FileAWS" asp-controller="UploadFile"
               asp-route-filename="@file" class="btn btn-info">
                View @file File
            </a>
        </li>
        <li class="list-group-item">
            <a asp-action="FileImg" asp-controller="UploadFile"
               asp-route-filename="@file" class="btn btn-secondary">
                Imagen @file ver
            </a>
        </li>
    }
</ul>
}
else
{
    <h1 style="color:red"> No hay fichero en el Bucket</h1>
}

MvcCoreS3Post/Views/UploadFile/Upload.cshtml
<h1 style="color:firebrick">
    Upload file AWS
</h1>

<a asp-action="Index" asp-controller="AWSFile">
    Volver Index
</a>

<form method="post" enctype="multipart/form-data">
    <label>Seleccionar fichero</label>
    <input type="file" name="file" class="form-control-file" />
    <button type="submit" class="btn-outline-info">
        Upload File
    </button>
</form>

MvcCoreS3Post/Views/UploadFile/UploadChangeName.cshtml
<h1 style="color:firebrick">
    Upload file AWS Cambiando el nombre
</h1>

<a asp-action="Index" asp-controller="AWSFile">
    Volver Index
</a>

<form method="post" enctype="multipart/form-data">
    <label>Seleccionar fichero</label>
    <input type="file" name="file" class="form-control-file" />
    <button type="submit" class="btn-outline-info">
        Upload File
    </button>
</form>

MvcCoreS3Post/Views/UploadFile/UploadDirectory.cshtml
<h1 style="color:firebrick">
    Upload file AWS a un directorio del bucket
</h1>

<a asp-action="Index" asp-controller="AWSFile">
    Volver Index
</a>

<form method="post" enctype="multipart/form-data">
    <label>Seleccionar fichero</label>
    <input type="file" name="file" class="form-control-file" />
    <button type="submit" class="btn-outline-info">
        Upload File
    </button>
</form>